### ISSUE TITLE
윈도우 버전에서 이미지 압축 기능 에러

### ISSUE THREAD

**Issue by occidere** [occidere/MMDownloader#77]
# 윈도우 버전에서 이미지 압축 기능 에러

````
2018-07-30_00-00-47_다운받은_만화_압축_실패.txt

java.util.zip.ZipException: duplicate entry: 
	at java.util.zip.ZipOutputStream.putNextEntry(Unknown Source)
	at util.ImageCompress.compress(ImageCompress.java:47)
	at util.ImageCompress.compress(ImageCompress.java:26)
	at downloader.Downloader.download(Downloader.java:167)
	at downloader.Preprocess.connector(Preprocess.java:54)
	at ui.UI.showMenu(UI.java:63)
	at main.Main.main(Main.java:9)
````
* 압축 파일명이 `.zip`으로만 되어있는것으로 보아 StringUtils 사용 과정에서 발생한 에러로 추정

**Comment by occidere** [comment]
원인: windows인데도 경로 구분자를 `/`로 직접 지정하여 사용하고 있어서 `File.separator` 가 먹히지 않음

**Comment by occidere** [comment]
수정완료
